In [2]:
import torch
import torch.nn as nn

In [3]:
# 定义一个全连接层
linear = nn.Linear(5, 2)

In [4]:
# 1. 常数初始化
nn.init.zeros_(linear.weight)
print(linear.weight)

Parameter containing:
tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]], requires_grad=True)


In [5]:
nn.init.ones_(linear.bias)
print(linear.bias)

Parameter containing:
tensor([1., 1.], requires_grad=True)


In [6]:
nn.init.constant_(linear.weight, 10)
print(linear.weight)

Parameter containing:
tensor([[10., 10., 10., 10., 10.],
        [10., 10., 10., 10., 10.]], requires_grad=True)


In [7]:
# 2. 秩初始化
nn.init.eye_(linear.weight)
print(linear.weight)

Parameter containing:
tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.]], requires_grad=True)


In [11]:
# 3. 正态分布初始化
nn.init.normal_(linear.weight, mean=0, std=1)
print(linear.weight)

Parameter containing:
tensor([[-0.2791,  0.4977,  1.2483,  1.4257,  0.4294],
        [ 0.7032,  0.7668, -0.7557,  0.2267,  0.0488]], requires_grad=True)


In [9]:
# 4. 均匀分布初始化
nn.init.uniform_(linear.weight, a=-3.0, b=3.0)
print(linear.weight)

Parameter containing:
tensor([[ 0.7612,  1.5005, -0.8193, -0.6694, -0.4147],
        [-1.4258,  1.1773,  0.1124, -0.5411, -2.3885]], requires_grad=True)


In [10]:
# 5. Xavier初始化
nn.init.xavier_normal_(linear.weight)
print(linear.weight)

Parameter containing:
tensor([[ 0.4398, -0.3321, -0.7419, -0.0090, -0.0665],
        [-0.1114,  0.0618,  0.9031,  0.7744,  0.2060]], requires_grad=True)


In [12]:
nn.init.xavier_uniform_(linear.weight)
print(linear.weight)

Parameter containing:
tensor([[ 0.6146,  0.7845, -0.9035,  0.3105,  0.8428],
        [ 0.2845, -0.3401, -0.4099,  0.5693, -0.9025]], requires_grad=True)


In [13]:
# 6. He初始化
nn.init.kaiming_normal_(linear.weight)
print(linear.weight)

Parameter containing:
tensor([[-1.1652, -0.3739, -0.3514,  1.2388,  0.4072],
        [-0.0106,  0.0573,  0.7374, -1.3059, -0.6208]], requires_grad=True)


In [14]:
nn.init.kaiming_uniform_(linear.weight)
print(linear.weight)

Parameter containing:
tensor([[ 0.9356, -0.3351,  0.3400, -0.1544, -0.1657],
        [-0.6796, -0.2392,  0.6658, -0.7797,  0.9193]], requires_grad=True)


In [26]:
input = torch.randn(1, 5, device='cuda')
print(input.device)

cuda:0


In [32]:
input = torch.tensor([[1, 2, 3], [4, 5, 6]], device='cpu').to(device='cuda')
print(input.device)

cuda:0
