In [1]:
import torch
import torch.nn as nn

In [9]:
# 定义RNN层
rnn = nn.RNN(input_size=8, hidden_size=16, num_layers=2, batch_first=True)

In [14]:
# 定义输入数据和初始隐状态
input = torch.randn(3, 3, 8)
hx = torch.randn(2, 3, 16)
print(input)
print(hx)

tensor([[[-1.1118, -0.5237,  0.5802,  0.2701,  0.1147,  2.4141,  0.5909,
          -0.2457],
         [ 0.0957, -0.3861, -1.0785, -1.0144, -0.3338,  1.6083, -2.0303,
           0.9453],
         [ 0.6607, -0.3648,  0.8523,  0.1530,  0.4775, -1.1641,  1.6601,
           0.4679]],

        [[ 1.3967, -1.0512,  0.9669,  1.9878,  1.1070, -1.4673, -0.7988,
           0.2173],
         [-1.2422, -0.1110,  0.9056, -0.3358,  0.1696, -0.4182,  0.9068,
          -0.5970],
         [ 0.5777, -1.1521,  0.7662, -1.3746,  0.1644,  1.2554,  0.4415,
           0.7155]],

        [[-0.4434,  0.6092,  1.0218, -0.3791,  0.9650, -0.9079, -0.4826,
          -2.0566],
         [ 0.6996,  0.0516, -0.0220,  1.2619,  0.9182,  0.5717, -0.7147,
          -0.8308],
         [-0.2932, -1.2811, -0.0593, -0.3811, -0.1722, -0.7583,  1.8990,
           0.7096]]])
tensor([[[ 0.1513,  0.7097,  0.0189, -0.7498,  1.0241,  0.8554, -1.2705,
           0.4125,  0.2574,  2.1273, -0.0244, -0.8666,  0.4494, -0.5839,
           

In [13]:
# 前向传播，得到输出和隐状态
output, hn = rnn(input, hx)
print(output)
print(hn)
print(output.shape)
print(hn.shape)

tensor([[[-2.8822e-01,  5.7195e-01, -3.4283e-01,  7.0772e-01, -7.8981e-01,
          -6.3703e-02,  1.3452e-01,  4.3229e-01,  6.0214e-01, -2.1144e-01,
          -7.0707e-01, -1.7375e-01,  4.5365e-01, -9.0084e-01,  4.8320e-01,
          -8.7710e-01,  2.3937e-02,  9.4793e-02,  7.7845e-01, -2.5041e-01],
         [-1.2436e-01, -5.7290e-02, -5.5758e-01,  6.3629e-01,  2.7443e-02,
          -6.8468e-01,  2.5516e-01,  3.6901e-01,  1.5441e-01, -3.8183e-01,
           5.9251e-01, -5.6009e-01, -2.2794e-01, -5.2570e-01, -2.5835e-01,
          -6.4588e-02, -3.7384e-01, -2.5549e-01,  9.2370e-02, -8.0913e-01],
         [ 1.1307e-02,  6.3261e-02, -1.4851e-01,  2.1340e-01, -2.9108e-01,
          -3.5407e-01, -1.3588e-01,  4.9464e-01,  3.7433e-01, -1.5922e-01,
           5.8995e-01, -7.2492e-01,  1.2762e-01, -6.4778e-01,  3.1590e-02,
          -2.0173e-01, -3.4334e-01,  2.7128e-01, -6.6041e-02, -4.9339e-01]],

        [[-3.1430e-01, -1.6084e-01,  5.2166e-01,  4.2476e-01,  7.5465e-01,
          -1.6830e-0