In [1]:
import torch
import torch.nn as nn

In [4]:
# 1. 目标值为顺序编码的标签
input = torch.randn(6, 8)
print(input)
# pred = torch.softmax(input, dim=1)
# print(pred)

tensor([[ 1.7448e-01, -9.3142e-01, -1.0742e+00,  1.1708e-01,  6.5897e-02,
          1.2158e+00,  3.3754e-01, -8.9479e-01],
        [-6.0745e-01,  7.3669e-01, -7.3768e-01,  1.7372e-03,  3.7786e-02,
          9.5485e-01, -5.3845e-01,  1.2284e+00],
        [-3.3120e-01, -2.2824e+00, -5.3278e-01, -1.4454e+00, -4.7627e-01,
          4.8418e-01, -7.2850e-02,  4.0925e-01],
        [ 8.1462e-01,  1.0913e+00, -6.3417e-01, -3.6658e-02,  7.4988e-01,
          1.1976e+00, -1.5674e+00,  1.6647e-01],
        [ 1.9260e-01,  1.5223e-01,  2.0694e-01,  7.5987e-01,  1.3489e+00,
         -1.3800e-01,  1.3885e+00,  4.4616e-01],
        [-2.0842e+00,  6.5592e-01,  7.7726e-01,  1.7244e+00, -1.2529e+00,
         -2.1969e-01, -1.8530e+00,  3.0523e-01]])
tensor([[0.1280, 0.0424, 0.0367, 0.1209, 0.1148, 0.3626, 0.1507, 0.0439],
        [0.0464, 0.1778, 0.0407, 0.0853, 0.0884, 0.2211, 0.0497, 0.2907],
        [0.1136, 0.0161, 0.0928, 0.0373, 0.0982, 0.2567, 0.1471, 0.2382],
        [0.1667, 0.2198, 0.0391, 0.0711

In [3]:
# 目标值，6个数据的类别标签（0~7）
target = torch.tensor([1, 0, 3, 7, 5, 2])
print(target)

tensor([1, 0, 3, 7, 5, 2])


In [6]:
# 定义损失函数
loss = nn.CrossEntropyLoss()
print(loss(input, target))

tensor(2.7698)


In [7]:
# 2. 目标值为一组概率（独热编码）
input = torch.randn(6, 8)
print(input)

tensor([[-0.3806, -1.0685,  0.1297, -0.2744,  0.6278,  1.0084, -0.0295, -0.1174],
        [-0.7710, -0.0833, -0.5224,  0.1119,  1.1353,  0.5080, -0.3516,  0.7344],
        [ 0.1122,  0.6168, -0.1664, -0.6604, -0.1560,  2.3544,  0.3451,  0.3870],
        [ 0.1673, -0.7665,  0.4577,  0.5243,  0.2638, -0.4391, -1.4458, -0.0529],
        [-1.2748, -1.3672,  0.6418,  0.1724,  0.8483,  1.2101,  0.5239, -1.6376],
        [-0.3037, -0.9512, -0.0461, -0.0463, -1.8956, -0.5862, -0.1464,  0.3490]])


In [8]:
target = torch.randn(6, 8).softmax(dim=1)
print(target)

tensor([[0.0865, 0.0952, 0.3451, 0.0138, 0.0732, 0.0564, 0.2225, 0.1073],
        [0.0761, 0.1262, 0.1048, 0.4887, 0.0370, 0.0887, 0.0459, 0.0327],
        [0.2508, 0.0482, 0.0827, 0.1330, 0.0822, 0.0510, 0.0717, 0.2804],
        [0.1244, 0.1608, 0.0232, 0.1208, 0.0252, 0.2202, 0.2246, 0.1009],
        [0.1113, 0.0243, 0.0596, 0.3978, 0.1610, 0.0614, 0.1438, 0.0408],
        [0.1349, 0.1208, 0.0551, 0.1922, 0.1852, 0.1437, 0.1217, 0.0464]])


In [9]:
loss = nn.CrossEntropyLoss()
print(loss(input, target))

tensor(2.4193)
