In [1]:
import torch
import numpy as np

6.4.1 张量元素类型转换

In [2]:
tensor1 = torch.tensor([1, 2, 3])
print(tensor1.dtype)

torch.int64


In [4]:
tensor1 = tensor1.type(torch.float64)
print(tensor1.dtype)

torch.float64


In [5]:
tensor1 = tensor1.half()
print(tensor1.dtype)

torch.float16


In [6]:
print(tensor1)

tensor([1., 2., 3.], dtype=torch.float16)


In [9]:
tensor1 = tensor1.to(torch.complex64)
print(tensor1, tensor1.dtype)

tensor([1.+0.j, 2.+0.j, 3.+0.j]) torch.complex64


6.4.2 Tensor与ndarray转换

In [12]:
np.set_printoptions(precision=6)
torch.set_printoptions(precision=6)

# 1. tensor → ndarray
tensor1 = torch.rand(3, 2)
print(tensor1)

tensor([[0.850176, 0.024523],
        [0.085884, 0.428618],
        [0.760745, 0.007659]])


In [13]:
ndarray1 = tensor1.numpy()
print(ndarray1)

[[0.850176 0.024523]
 [0.085884 0.428618]
 [0.760745 0.007659]]


In [14]:
tensor1[:, 0] = 10
print(tensor1)
print(ndarray1)

tensor([[1.000000e+01, 2.452344e-02],
        [1.000000e+01, 4.286180e-01],
        [1.000000e+01, 7.658958e-03]])
[[1.000000e+01 2.452344e-02]
 [1.000000e+01 4.286180e-01]
 [1.000000e+01 7.658958e-03]]


In [15]:
# 使用copy方法避免共享内存
ndarray2 = tensor1.numpy().copy()
print(ndarray2)

[[1.000000e+01 2.452344e-02]
 [1.000000e+01 4.286180e-01]
 [1.000000e+01 7.658958e-03]]


In [16]:
tensor1[:, 0] = 5
print(tensor1)
print(ndarray1)
print(ndarray2)

tensor([[5.000000, 0.024523],
        [5.000000, 0.428618],
        [5.000000, 0.007659]])
[[5.       0.024523]
 [5.       0.428618]
 [5.       0.007659]]
[[1.000000e+01 2.452344e-02]
 [1.000000e+01 4.286180e-01]
 [1.000000e+01 7.658958e-03]]


In [17]:
# 2. ndarray → tensor
ndarray1 = np.random.randn(3, 2)
tensor1 = torch.from_numpy(ndarray1)
print(tensor1)
print(ndarray1)

tensor([[ 1.595886,  2.343617],
        [-1.596200, -0.249499],
        [-0.706414,  0.201605]], dtype=torch.float64)
[[ 1.595886  2.343617]
 [-1.5962   -0.249499]
 [-0.706414  0.201605]]


In [18]:
ndarray1[:, 0] = 5
print(tensor1)
print(ndarray1)

tensor([[ 5.000000,  2.343617],
        [ 5.000000, -0.249499],
        [ 5.000000,  0.201605]], dtype=torch.float64)
[[ 5.        2.343617]
 [ 5.       -0.249499]
 [ 5.        0.201605]]


In [19]:
# 使用copy方法避免内存共享
tensor2 = torch.from_numpy(ndarray1.copy())
ndarray1[:, 0] = 7
print(ndarray1)
print(tensor1)
print(tensor2)

[[ 7.        2.343617]
 [ 7.       -0.249499]
 [ 7.        0.201605]]
tensor([[ 7.000000,  2.343617],
        [ 7.000000, -0.249499],
        [ 7.000000,  0.201605]], dtype=torch.float64)
tensor([[ 5.000000,  2.343617],
        [ 5.000000, -0.249499],
        [ 5.000000,  0.201605]], dtype=torch.float64)


In [20]:
# 使用tensor方法直接转换成Tensor
ndarray1 = np.random.randn(3, 2)
tensor1 = torch.tensor(ndarray1)
print(tensor1)
print(ndarray1)

tensor([[ 0.959055,  0.274547],
        [-1.169599,  0.423460],
        [ 0.174319, -0.702705]], dtype=torch.float64)
[[ 0.959055  0.274547]
 [-1.169599  0.42346 ]
 [ 0.174319 -0.702705]]


In [21]:
ndarray1[:, 0] = 5
print(tensor1)
print(ndarray1)

tensor([[ 0.959055,  0.274547],
        [-1.169599,  0.423460],
        [ 0.174319, -0.702705]], dtype=torch.float64)
[[ 5.        0.274547]
 [ 5.        0.42346 ]
 [ 5.       -0.702705]]


In [22]:
# 张量与标量的转换
tensor1 = torch.tensor(10)
print(tensor1)

tensor(10)


In [23]:
print( tensor1.item() )

10


In [26]:
tensor1 = torch.tensor([[10]])
print(tensor1)
print( tensor1.item() )

tensor([[10]])
10
