In [1]:
import torch

In [2]:
# 1. 四则运算
tensor1 = torch.randint(low=0, high=10, size=(2,3))
print(tensor1)

tensor([[4, 2, 1],
        [6, 3, 1]])


In [3]:
print(tensor1 + 10)

tensor([[14, 12, 11],
        [16, 13, 11]])


In [4]:
print(tensor1.add(10))

tensor([[14, 12, 11],
        [16, 13, 11]])


In [5]:
print(tensor1)

tensor([[4, 2, 1],
        [6, 3, 1]])


In [6]:
print(tensor1.add_(10))
print(tensor1)

tensor([[14, 12, 11],
        [16, 13, 11]])
tensor([[14, 12, 11],
        [16, 13, 11]])


In [7]:
print(tensor1.sub_(10))

tensor([[4, 2, 1],
        [6, 3, 1]])


In [8]:
# 幂函数
print(tensor1 ** 2)

tensor([[16,  4,  1],
        [36,  9,  1]])


In [9]:
print(tensor1.pow(2))
print(tensor1)

tensor([[16,  4,  1],
        [36,  9,  1]])
tensor([[4, 2, 1],
        [6, 3, 1]])


In [10]:
print(tensor1.pow_(2))
print(tensor1)

tensor([[16,  4,  1],
        [36,  9,  1]])
tensor([[16,  4,  1],
        [36,  9,  1]])


In [11]:
print(tensor1.sqrt())

tensor([[4., 2., 1.],
        [6., 3., 1.]])


In [12]:
print(tensor1)

tensor([[16,  4,  1],
        [36,  9,  1]])


In [14]:
tensor1 = tensor1.float()
print(tensor1.sqrt_())
print(tensor1)

tensor([[4., 2., 1.],
        [6., 3., 1.]])
tensor([[4., 2., 1.],
        [6., 3., 1.]])


In [17]:
tensor1 = torch.tensor([1.0, 2, 3])
print(tensor1)
print(2.7182818 ** tensor1)

tensor([1., 2., 3.])
tensor([ 2.7183,  7.3891, 20.0855])


In [18]:
print(tensor1.exp())

tensor([ 2.7183,  7.3891, 20.0855])


In [19]:
print(tensor1)
print(tensor1.exp_())
print(tensor1)

tensor([1., 2., 3.])
tensor([ 2.7183,  7.3891, 20.0855])
tensor([ 2.7183,  7.3891, 20.0855])


In [20]:
# 计算张量的哈达玛积
tensor1 = torch.tensor([[1, 2], [3, 4]])
tensor2 = torch.tensor([[1, 2], [3, 4]])
print(tensor1 + tensor2)
print(tensor1 * tensor2)

tensor([[2, 4],
        [6, 8]])
tensor([[ 1,  4],
        [ 9, 16]])


In [21]:
print(tensor1.mul(tensor2))

tensor([[ 1,  4],
        [ 9, 16]])


In [22]:
# 张量乘法
tensor1 = torch.tensor([[1, 2, 3], [4, 5, 6]])
tensor2 = torch.tensor([[1, 2], [3, 4], [5, 6]])
print(tensor1 @ tensor2)

tensor([[22, 28],
        [49, 64]])


In [23]:
print(tensor1.matmul(tensor2))

tensor([[22, 28],
        [49, 64]])


In [24]:
print(tensor1.mm(tensor2))

tensor([[22, 28],
        [49, 64]])


In [25]:
tensor1 = torch.tensor([[[1, 2, 3], [4, 5, 6]], [[6, 5, 4], [3, 2, 1]]])
tensor2 = torch.tensor([[[1, 2], [3, 4], [5, 6]], [[6, 5], [4, 3], [2, 1]]])
print(tensor1 @ tensor2)
print(tensor1.matmul(tensor2))

tensor([[[22, 28],
         [49, 64]],

        [[64, 49],
         [28, 22]]])
tensor([[[22, 28],
         [49, 64]],

        [[64, 49],
         [28, 22]]])


In [44]:
# print(tensor1.mm(tensor2))
tensor1 = torch.randn(4, 2, 2, 3)
tensor2 = torch.randn(1, 1, 3, 5)
tensor3 = tensor1 @ tensor2
print(tensor3.shape)

torch.Size([4, 2, 2, 5])


In [32]:
# 验证内存的共享和节省内存
X = torch.randint(1, 10, (3, 2, 4))
print(X)
print(id(X))

tensor([[[9, 4, 7, 6],
         [8, 3, 5, 6]],

        [[8, 2, 2, 1],
         [1, 7, 6, 4]],

        [[4, 5, 4, 2],
         [6, 4, 9, 3]]])
2860811136896


In [33]:
# X = X + 10
X += 10
print(X)
print(id(X))

tensor([[[19, 14, 17, 16],
         [18, 13, 15, 16]],

        [[18, 12, 12, 11],
         [11, 17, 16, 14]],

        [[14, 15, 14, 12],
         [16, 14, 19, 13]]])
2860811136896


In [45]:
X = torch.randint(1, 10, (3, 2, 4))
Y = torch.randint(1, 10, (3, 4, 1))
print(X.shape)
print(id(X))
print(X)
print(Y)
print(X @ Y)
# X = X @ Y
# X @= Y
X[:] = X @ Y
print(X.shape)
print(X)
print(id(X))

torch.Size([3, 2, 4])
2860811448592
tensor([[[2, 6, 8, 7],
         [5, 4, 3, 2]],

        [[6, 2, 7, 5],
         [6, 6, 7, 9]],

        [[5, 2, 3, 6],
         [1, 4, 8, 2]]])
tensor([[[7],
         [8],
         [4],
         [5]],

        [[7],
         [1],
         [6],
         [7]],

        [[9],
         [1],
         [8],
         [6]]])
tensor([[[129],
         [ 89]],

        [[121],
         [153]],

        [[107],
         [ 89]]])
torch.Size([3, 2, 4])
tensor([[[129, 129, 129, 129],
         [ 89,  89,  89,  89]],

        [[121, 121, 121, 121],
         [153, 153, 153, 153]],

        [[107, 107, 107, 107],
         [ 89,  89,  89,  89]]])
2860811448592
