In [1]:
import torch

In [2]:
tensor1 = torch.randint(1, 10, (3, 5, 4))
print(tensor1)

tensor([[[8, 4, 7, 4],
         [8, 6, 9, 7],
         [9, 5, 8, 5],
         [3, 7, 4, 7],
         [5, 2, 4, 2]],

        [[8, 7, 6, 5],
         [3, 9, 2, 9],
         [3, 5, 1, 1],
         [6, 6, 4, 9],
         [8, 6, 7, 6]],

        [[8, 7, 2, 5],
         [8, 3, 6, 7],
         [1, 2, 9, 6],
         [4, 3, 5, 6],
         [8, 3, 7, 8]]])


In [3]:
# 1. 简单索引
print(tensor1[2, 1, 3])

tensor(7)


In [4]:
print(tensor1[2, 3])

tensor([4, 3, 5, 6])


In [5]:
print(tensor1[1])

tensor([[8, 7, 6, 5],
        [3, 9, 2, 9],
        [3, 5, 1, 1],
        [6, 6, 4, 9],
        [8, 6, 7, 6]])


In [6]:
print(tensor1[:, 3])

tensor([[3, 7, 4, 7],
        [6, 6, 4, 9],
        [4, 3, 5, 6]])


In [7]:
# 2. 范围索引
print(tensor1[1:])

tensor([[[8, 7, 6, 5],
         [3, 9, 2, 9],
         [3, 5, 1, 1],
         [6, 6, 4, 9],
         [8, 6, 7, 6]],

        [[8, 7, 2, 5],
         [8, 3, 6, 7],
         [1, 2, 9, 6],
         [4, 3, 5, 6],
         [8, 3, 7, 8]]])


In [8]:
print(tensor1[-1:, 1:4, 0:3])

tensor([[[8, 3, 6],
         [1, 2, 9],
         [4, 3, 5]]])


In [10]:
print(tensor1[-1:, 1:4:2, 0:3:2])

tensor([[[8, 6],
         [4, 5]]])


In [13]:
# print(tensor1[-1:, 4:1:-2, 0:3:2])
print(tensor1[-1:, -4:-1:2, 0:3:2])

tensor([[[8, 6],
         [4, 5]]])


In [15]:
# 3. 列表索引
print(tensor1[[0, 1], [3, 2]])

tensor([[3, 7, 4, 7],
        [3, 5, 1, 1]])


In [17]:
print(tensor1[[0, 1], [3, 2], [2, 3]])

tensor([4, 1])


In [18]:
print(tensor1[[[0], [1]], [1, 2]])

tensor([[[8, 6, 9, 7],
         [9, 5, 8, 5]],

        [[3, 9, 2, 9],
         [3, 5, 1, 1]]])


In [19]:
# 4. 布尔索引
# 4.1 选取符合条件的行：首元素大于5
mask = tensor1[:, :, 0] > 5
print(mask)

tensor([[ True,  True,  True, False, False],
        [ True, False, False,  True,  True],
        [ True,  True, False, False,  True]])


In [20]:
print(tensor1[mask])

tensor([[8, 4, 7, 4],
        [8, 6, 9, 7],
        [9, 5, 8, 5],
        [8, 7, 6, 5],
        [6, 6, 4, 9],
        [8, 6, 7, 6],
        [8, 7, 2, 5],
        [8, 3, 6, 7],
        [8, 3, 7, 8]])


In [21]:
# 4.2 选取符合条件的列：第二个元素大于5
mask = tensor1[:, 1, :] > 5
print(mask)

tensor([[ True,  True,  True,  True],
        [False,  True, False,  True],
        [ True, False,  True,  True]])


In [24]:
# print(tensor1[mask])
tensor2 = tensor1.mT
print(tensor2)

tensor([[[8, 8, 9, 3, 5],
         [4, 6, 5, 7, 2],
         [7, 9, 8, 4, 4],
         [4, 7, 5, 7, 2]],

        [[8, 3, 3, 6, 8],
         [7, 9, 5, 6, 6],
         [6, 2, 1, 4, 7],
         [5, 9, 1, 9, 6]],

        [[8, 8, 1, 4, 8],
         [7, 3, 2, 3, 3],
         [2, 6, 9, 5, 7],
         [5, 7, 6, 6, 8]]])


In [26]:
# 将mask应用到tensor2上，形状匹配前两个维度
print(tensor2[mask].mT)

tensor([[8, 4, 7, 4, 7, 5, 8, 2, 5],
        [8, 6, 9, 7, 9, 9, 8, 6, 7],
        [9, 5, 8, 5, 5, 1, 1, 9, 6],
        [3, 7, 4, 7, 6, 9, 4, 5, 6],
        [5, 2, 4, 2, 6, 6, 8, 7, 8]])


In [27]:
# 4.3 选取符合条件的矩阵: 元素（1,2）>5
mask = tensor1[:, 1, 2] > 5
print(mask)

tensor([ True, False,  True])


In [28]:
print(tensor1[mask])

tensor([[[8, 4, 7, 4],
         [8, 6, 9, 7],
         [9, 5, 8, 5],
         [3, 7, 4, 7],
         [5, 2, 4, 2]],

        [[8, 7, 2, 5],
         [8, 3, 6, 7],
         [1, 2, 9, 6],
         [4, 3, 5, 6],
         [8, 3, 7, 8]]])


In [31]:
mask = tensor1 > 5
print(mask)

tensor([[[ True, False,  True, False],
         [ True,  True,  True,  True],
         [ True, False,  True, False],
         [False,  True, False,  True],
         [False, False, False, False]],

        [[ True,  True,  True, False],
         [False,  True, False,  True],
         [False, False, False, False],
         [ True,  True, False,  True],
         [ True,  True,  True,  True]],

        [[ True,  True, False, False],
         [ True, False,  True,  True],
         [False, False,  True,  True],
         [False, False, False,  True],
         [ True, False,  True,  True]]])


In [32]:
print(tensor1[mask])

tensor([8, 7, 8, 6, 9, 7, 9, 8, 7, 7, 8, 7, 6, 9, 9, 6, 6, 9, 8, 6, 7, 6, 8, 7,
        8, 6, 7, 9, 6, 6, 8, 7, 8])
