In [7]:
import torch

In [8]:
# 定义数据
x = torch.tensor(10.0)
y = torch.tensor([[3.0]])
print(x)
print(y)

tensor(10.)
tensor([[3.]])


In [9]:
# 初始化参数
w = torch.rand(1, 1, requires_grad=True)
b = torch.rand(1, 1, requires_grad=True)

In [10]:
# 前向传播，得到输出
z = w * x + b
print(z)

tensor([[5.6091]], grad_fn=<AddBackward0>)


In [11]:
print(x.is_leaf)
print(w.is_leaf)
print(b.is_leaf)
print(y.is_leaf)
print(z.is_leaf)

True
True
True
True
False


In [12]:
# 设置损失函数
loss = torch.nn.MSELoss()
loss_value = loss(z, y)
print(loss_value)
print(loss_value.is_leaf)

tensor(6.8073, grad_fn=<MseLossBackward0>)
False


In [13]:
# 反向传播
loss_value.backward()

In [17]:
# 查看梯度
print(w.grad)
print(b.grad)

tensor([[52.1817]])
tensor([[5.2182]])
